"use client"

import { useState, useEffect } from 'react'
import { devLog } from '@/lib/devLogger';
import { useAuth } from '@/hooks/use-auth'
import type { AdditionalProfile, CompatibilityReport } from '@/lib/types/profileTypes'
import { ProfileList } from '@/components/profiles/ProfileList'
import { CompatibilityReport as CompatibilityReportComponent } from '@/components/compatibility/CompatibilityReport'
import { TipJarEncouragement } from '@/components/compatibility/TipJarEncouragement'
import { calculateCompatibility } from '@/lib/services/compatibilityService'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Loader2, Users, Sparkles, AlertCircle } from 'lucide-react'
import { useToast } from '@/hooks/use-toast'
import { useRouter } from 'next/navigation'
import Link from 'next/link'

interface CompatibilityTabProps {
  toolSlug: string
}

const PROFILE_LOAD_TIMEOUT_MS = 5000

export function CompatibilityTab({ toolSlug }: CompatibilityTabProps) {
  const { user, userProfile } = useAuth()
  const { toast } = useToast()
  const router = useRouter()
  const [selectedProfile, setSelectedProfile] = useState<AdditionalProfile | null>(null)
  const [report, setReport] = useState<CompatibilityReport | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [autoGenerated, setAutoGenerated] = useState(false) // Track if report was auto-generated
  const [comparisonCount, setComparisonCount] = useState(0)
  const [showTipJarEncouragement, setShowTipJarEncouragement] = useState(false)
  const [profileLoadTimedOut, setProfileLoadTimedOut] = useState(false)

  useEffect(() => {
    if (userProfile) {
      setProfileLoadTimedOut(false)
      return
    }
    const t = setTimeout(() => setProfileLoadTimedOut(true), PROFILE_LOAD_TIMEOUT_MS)
    return () => clearTimeout(t)
  }, [userProfile])

  useEffect(() => {
    // Clear report when profile changes (unless it was just auto-generated)
    if (!autoGenerated) {
      setReport(null)
    }
    setAutoGenerated(false)
  }, [selectedProfile, autoGenerated])

  const handleGenerateReport = async (profile?: AdditionalProfile) => {
    const profileToUse = profile || selectedProfile
    
    if (!userProfile || !profileToUse) {
      toast({
        title: 'Missing Information',
        description: 'Please ensure your profile is complete and select a profile to compare.',
        variant: 'destructive'
      })
      return
    }

    if (!userProfile.birthDate) {
      toast({
        title: 'Profile Incomplete',
        description: 'Please complete your birth date in your profile to generate compatibility reports.',
        variant: 'destructive'
      })
      return
    }

    // Select the profile if it was just saved
    if (profile && !selectedProfile) {
      setSelectedProfile(profile)
    }

    setIsGenerating(true)
    try {
      const compatibilityReport = await calculateCompatibility(
        toolSlug,
        userProfile,
        profileToUse
      )
      setReport(compatibilityReport)
      
      // If this was triggered from Save and Generate, mark as auto-generated
      if (profile) {
        setAutoGenerated(true)
      }
      
      // Increment comparison count and show tip jar after first free comparison
      setComparisonCount(prev => {
        const newCount = prev + 1
        if (newCount > 1) {
          setShowTipJarEncouragement(true)
        }
        return newCount
      })
      
      toast({
        title: 'Report Generated',
        description: comparisonCount === 0 
          ? 'Your first comparison is complete! Enjoy it on us.' 
          : 'Compatibility analysis completed successfully.',
      })
    } catch (error: any) {
      devLog.error('Error generating compatibility report:', error, 'CompatibilityTab')
      toast({
        title: 'Error',
        description: error.message || 'Failed to generate compatibility report. Please try again.',
        variant: 'destructive'
      })
    } finally {
      setIsGenerating(false)
    }
  }

  const handleSaveAndGenerate = async (profile: AdditionalProfile) => {
    // Profile is already saved by AdditionalProfileForm
    // Select the profile and generate the report immediately
    setSelectedProfile(profile)
    await handleGenerateReport(profile)
  }

  const handleSelectPlan = (planId: 'buy-coffee' | 'treat-me' | 'festive-hamper') => {
    // Navigate to signup/subscribe page with selected plan
    router.push(`/subscribe?plan=${planId}`)
  }

  const handleDismissTipJar = () => {
    setShowTipJarEncouragement(false)
  }

  if (!user?.uid) {
    return (
      <Card className="glass-card border-white/10 backdrop-blur-sm rounded-3xl">
        <CardContent className="flex flex-col items-center justify-center py-12">
          <Users className="w-16 h-16 text-slate-300 mb-4" />
          <p className="text-slate-200 mb-4">Please sign in to use compatibility analysis</p>
        </CardContent>
      </Card>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <Card className="bg-gradient-to-br from-purple-50 via-pink-50 to-amber-50 border-2 border-purple-200 shadow-lg rounded-3xl">
        <CardHeader>
          <CardTitle className="flex items-center gap-3 text-purple-900">
            <div className="bg-purple-200/60 rounded-full p-2">
              <Users className="w-6 h-6 text-purple-700" />
            </div>
            <span>Compare Profiles</span>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-slate-700 text-sm leading-relaxed">
            Generate detailed compatibility reports showing strengths, challenges, and recommendations. 
            <strong className="text-purple-900"> Your first comparison is free!</strong> Support FutureSeer 
            to unlock unlimited comparisons.
          </p>
        </CardContent>
      </Card>

      {/* Side-by-Side Layout: User Profile + Profile Management */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left Side: User's Profile (Permanent) */}
        <div className="space-y-4">
          <h3 className="text-lg font-semibold text-slate-200 flex items-center gap-2">
            <div className="bg-amber-200/60 rounded-full p-1.5">
              <Sparkles className="w-4 h-4 text-amber-700" />
            </div>
            Your Profile
          </h3>
          {userProfile ? (
            <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 shadow-lg rounded-2xl">
              <CardContent className="p-5">
                <div>
                  <h4 className="text-xl font-bold text-amber-900 mb-3">
                    {userProfile.displayName || userProfile.fullName || 'Your Profile'}
                  </h4>
                  <div className="space-y-2 text-sm text-slate-700">
                    {userProfile.birthDate && (
                      <p className="flex items-center gap-2">
                        <span className="font-semibold text-amber-800">Born:</span>
                        {new Date(userProfile.birthDate).toLocaleDateString('en-US', { 
                          month: 'long', 
                          day: 'numeric', 
                          year: 'numeric' 
                        })}
                      </p>
                    )}
                    {userProfile.birthTime && (
                      <p className="flex items-center gap-2">
                        <span className="font-semibold text-amber-800">Time:</span>
                        {userProfile.birthTime}
                      </p>
                    )}
                    {userProfile.birthPlace && (
                      <p className="flex items-center gap-2">
                        <span className="font-semibold text-amber-800">Place:</span>
                        {userProfile.birthPlace}
                      </p>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>
          ) : profileLoadTimedOut ? (
            <Card className="bg-slate-800/50 border border-amber-500/20 rounded-2xl">
              <CardContent className="p-6 text-center">
                <AlertCircle className="w-10 h-10 text-amber-400 mx-auto mb-3" />
                <p className="text-slate-300 mb-3">Profile didn’t load. Open Profile to refresh.</p>
                <Button asChild variant="outline" className="border-amber-500/40 text-amber-200 hover:bg-amber-500/10">
                  <Link href="/profile">Open Profile</Link>
                </Button>
              </CardContent>
            </Card>
          ) : (
            <Card className="bg-slate-800/50 border border-amber-500/20 rounded-2xl">
              <CardContent className="p-6 flex items-center justify-center gap-3 text-slate-300">
                <Loader2 className="w-5 h-5 animate-spin shrink-0" />
                <span>Loading your profile…</span>
              </CardContent>
            </Card>
          )}

          {/* Comparison Profile Card (when selected but report not yet generated) */}
          {selectedProfile && !report && (
            <Card className="bg-gradient-to-br from-blue-50 to-cyan-50 border-2 border-blue-300 shadow-lg rounded-2xl">
              <CardHeader className="pb-3">
                <CardTitle className="flex items-center gap-2 text-blue-900 text-base">
                  <div className="bg-blue-200/60 rounded-full p-1.5">
                    <Users className="w-5 h-5 text-blue-700" />
                  </div>
                  Comparison Profile
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-0">
                <div className="space-y-4">
                  <div>
                    <h4 className="text-xl font-bold text-blue-900 mb-3">{selectedProfile.name}</h4>
                    <div className="space-y-2 text-sm text-slate-700">
                      <p className="flex items-center gap-2">
                        <span className="font-semibold text-blue-800">Born:</span>
                        {new Date(selectedProfile.dateOfBirth).toLocaleDateString('en-US', { 
                          month: 'long', 
                          day: 'numeric', 
                          year: 'numeric' 
                        })}
                      </p>
                      {selectedProfile.timeOfBirth && (
                        <p className="flex items-center gap-2">
                          <span className="font-semibold text-blue-800">Time:</span>
                          {selectedProfile.timeOfBirth}
                        </p>
                      )}
                      {selectedProfile.birthPlace && (
                        <p className="flex items-center gap-2">
                          <span className="font-semibold text-blue-800">Place:</span>
                          {selectedProfile.birthPlace}
                        </p>
                      )}
                    </div>
                  </div>
                  <Button
                    onClick={() => handleGenerateReport()}
                    disabled={isGenerating}
                    className="w-full bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-700 hover:to-cyan-700 text-white py-3 rounded-xl shadow-md"
                  >
                    {isGenerating ? (
                      <>
                        <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                        Generating Compatibility Report...
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-5 h-5 mr-2" />
                        {comparisonCount === 0 ? 'Generate Free Comparison' : 'Generate Comparison'}
                      </>
                    )}
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}
        </div>

        {/* Right Side: Profile Management (Add Profile & Profile List) */}
        <div className="space-y-4">
          <ProfileList
            userId={user.uid}
            onSelectProfile={setSelectedProfile}
            selectedProfileId={selectedProfile?.id}
            toolSlug={toolSlug}
            onSaveAndGenerate={handleSaveAndGenerate}
          />
        </div>
      </div>

      {/* Tip Jar Encouragement - Shows after first comparison */}
      {showTipJarEncouragement && (
        <TipJarEncouragement
          onSelectPlan={handleSelectPlan}
          onDismiss={handleDismissTipJar}
          countryCode={userProfile?.country || 'IN'}
        />
      )}

      {/* Report Display - One Page Comprehensive Report */}
      {report && (
        <div className="mt-6">
          <CompatibilityReportComponent report={report} />
        </div>
      )}
    </div>
  )
}

