"use client"

import { useState, useEffect, useMemo } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useAuth } from '@/hooks/use-auth'
import { useScrying } from '@/hooks/use-scrying'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Textarea } from '@/components/ui/textarea'
import { ToolIntroductionTab } from '@/components/ToolIntroductionTab'
import { ScrollArea } from '@/components/ui/scroll-area'
import ScryingSeerChatInterface from '@/components/ScryingSeerChatInterface'
import { 
  RefreshCw,
  AlertTriangle,
  Sparkles,
  Gem,
  Square,
  Info,
  User,
  Loader2,
  Star,
  Palette,
  Shapes,
  Image as ImageIcon,
  Wind,
  Target,
  Clock,
  Lightbulb,
  BookOpen,
  Compass,
  CheckCircle,
  MessageCircle
} from 'lucide-react'

export default function ScryingPage() {
  const { user, userProfile } = useAuth()
  const [activeTab, setActiveTab] = useState<'introduction' | 'overview' | 'session' | 'guidance' | 'ask-the-seer'>('introduction')
  const [isAutoGenerating, setIsAutoGenerating] = useState(false)
  
  const {
    question,
    setQuestion,
    method,
    setMethod,
    vision,
    autoGeneratedProfile,
    isLoading,
    isLoadingProfile,
    error,
    hasCompleteProfile,
    performScrying,
    generateAutoProfile,
    loadScryingProfile
  } = useScrying()

  // Auto-generate scrying profile when component loads and profile is complete
  useEffect(() => {
    const shouldAutoGenerate = 
      hasCompleteProfile && 
      !autoGeneratedProfile && 
      !isLoadingProfile && 
      !isAutoGenerating &&
      user?.uid

    if (shouldAutoGenerate) {
      setIsAutoGenerating(true)
      generateAutoProfile().finally(() => {
        setIsAutoGenerating(false)
      })
    }
  }, [hasCompleteProfile, autoGeneratedProfile, isLoadingProfile, isAutoGenerating, user?.uid])

  const scryingMethods = [
    { 
      value: 'crystal-ball' as const, 
      label: 'Crystal Ball', 
      icon: <Gem className="h-5 w-5" />,
      description: 'Gaze into the crystal sphere to receive visions',
    },
    { 
      value: 'mirror' as const, 
      label: 'Mirror Scrying', 
      icon: <Square className="h-5 w-5" />,
      description: 'Reflective surface divination for insights',
    }
  ]

  const currentVision = vision || autoGeneratedProfile
  const displayName = userProfile?.displayName || userProfile?.fullName || 'Seeker'

  // Check for reduced motion preference
  const prefersReducedMotion = useMemo(() => {
    if (typeof window === 'undefined') return false
    return window.matchMedia('(prefers-reduced-motion: reduce)').matches
  }, [])

  // Material 3 motion configuration
  const motionConfig = useMemo(() => {
    if (prefersReducedMotion) return { duration: 0 }
    return { duration: 0.3, ease: [0.4, 0, 0.2, 1] as [number, number, number, number] }
  }, [prefersReducedMotion])

  // Loading state
  if (isLoadingProfile || isAutoGenerating) {
    return (
      <div className="relative min-h-screen starfield-ultra-sharp">
        <div className="relative z-10 container mx-auto px-4 py-8 pt-4">
          <div className="flex items-center justify-center h-64">
            <div className="text-center">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-amber-400 mx-auto mb-4"></div>
              <p className="text-slate-200">Gazing into the vision for {displayName}...</p>
            </div>
          </div>
        </div>
      </div>
    )
  }

  // Error state
  if (error && !hasCompleteProfile) {
    return (
      <div className="relative min-h-screen starfield-ultra-sharp">
        <div className="relative z-10 container mx-auto px-4 py-8 pt-4">
          <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 shadow-lg rounded-3xl p-6 text-center max-w-2xl mx-auto">
            <AlertTriangle className="w-12 h-12 text-red-500 mx-auto mb-4" />
            <h3 className="text-amber-900 font-semibold mb-2 text-xl">Complete Your Profile</h3>
            <p className="text-slate-700 mb-4">
              Please complete your birth date, time, and place in your profile to generate your scrying profile.
            </p>
            <Button
              onClick={() => window.location.href = '/profile'}
              className="bg-amber-500 hover:bg-amber-600 text-white font-semibold rounded-xl"
            >
              <User className="w-4 h-4 mr-2" />
              Complete Profile
            </Button>
          </Card>
        </div>
      </div>
    )
  }

  return (
    <div className="relative min-h-screen starfield-ultra-sharp">
      {/* Content */}
      <div className="relative z-10 container mx-auto px-4 py-8">
        <div className="max-w-7xl mx-auto">
          {/* Header */}
          <div className="text-center mb-8 pt-4">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <h1 className="text-5xl font-serif font-semibold mb-8 flex items-center justify-center gap-3">
                <span className="text-4xl">🔮</span>
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-200 via-yellow-400 to-amber-600 pb-1 inline-block leading-tight">Scrying</span>
              </h1>
              <p className="text-slate-200 leading-relaxed text-xl font-light mt-2">
                Crystal ball and mirror scrying for divine visions and insights
              </p>
            </motion.div>
          </div>

          {/* Tabs */}
          <Tabs value={activeTab} onValueChange={(value) => setActiveTab(value as any)} className="w-full">
            <TabsList className="grid w-full grid-cols-5 bg-transparent p-0 gap-2">
              {[
                { value: 'introduction', label: 'Introduction', icon: BookOpen },
                { value: 'overview', label: 'Your Vision', icon: Gem },
                { value: 'session', label: 'Scrying Session', icon: Sparkles },
                { value: 'guidance', label: 'Guidance', icon: Compass },
                { value: 'ask-the-seer', label: 'Ask the Seer', icon: MessageCircle }
              ].map((tab) => {
                const Icon = tab.icon
                return (
                  <motion.div
                    key={tab.value}
                    whileHover={prefersReducedMotion ? {} : { scale: 1.02 }}
                    whileTap={prefersReducedMotion ? {} : { scale: 0.98 }}
                    transition={prefersReducedMotion ? {} : { type: "spring", stiffness: 400, damping: 17 }}
                    className="relative"
                  >
                    <TabsTrigger 
                      value={tab.value}
                      className="data-[state=active]:bg-gradient-to-br data-[state=active]:from-amber-100 data-[state=active]:to-yellow-100 data-[state=active]:text-amber-900 data-[state=active]:m3-elevation-1 rounded-xl px-4 py-2.5 text-sm font-medium text-slate-300 hover:text-slate-100 data-[state=inactive]:hover:bg-slate-800/30 transition-all flex items-center justify-center relative overflow-hidden"
                    >
                      <Icon className="w-4 h-4 mr-2" />
                      {tab.label}
                      {activeTab === tab.value && (
                        <motion.div
                          layoutId="activeTab"
                          className="absolute inset-0 bg-gradient-to-br from-amber-100 to-yellow-100 rounded-xl -z-10"
                          transition={prefersReducedMotion ? {} : { type: "spring", stiffness: 300, damping: 30 }}
                        />
                      )}
                    </TabsTrigger>
                  </motion.div>
                )
              })}
            </TabsList>

            {/* Tab Content with Material 3 Transitions */}
            <AnimatePresence mode="wait">
              {/* Introduction Tab */}
              {activeTab === 'introduction' && (
                <motion.div
                  key="introduction"
                  initial={prefersReducedMotion ? {} : { opacity: 0, y: 20 }}
                  animate={prefersReducedMotion ? {} : { opacity: 1, y: 0 }}
                  exit={prefersReducedMotion ? {} : { opacity: 0, y: -20 }}
                  transition={motionConfig}
                >
                  <TabsContent value="introduction" className="space-y-6 mt-6">
                    <ToolIntroductionTab toolSlug="scrying" />
                  </TabsContent>
                </motion.div>
              )}

              {/* Overview Tab - Auto-generated Profile */}
              {activeTab === 'overview' && (
                <motion.div
                  key="overview"
                  initial={prefersReducedMotion ? {} : { opacity: 0, y: 20 }}
                  animate={prefersReducedMotion ? {} : { opacity: 1, y: 0 }}
                  exit={prefersReducedMotion ? {} : { opacity: 0, y: -20 }}
                  transition={motionConfig}
                >
                  <TabsContent value="overview" className="space-y-6 mt-6">
                    {!hasCompleteProfile ? (
                      <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 shadow-lg rounded-3xl">
                        <CardContent className="p-6 text-center">
                          <Info className="w-12 h-12 text-amber-600 mx-auto mb-4" />
                          <h3 className="text-amber-900 font-semibold mb-2 text-xl">Complete Your Profile</h3>
                          <p className="text-slate-700 mb-4">
                            Please complete your birth date, time, and place to generate your personalized scrying profile.
                          </p>
                          <Button
                            onClick={() => window.location.href = '/profile'}
                            className="bg-amber-500 hover:bg-amber-600 text-white font-semibold rounded-xl"
                          >
                            <User className="w-4 h-4 mr-2" />
                            Complete Profile
                          </Button>
                        </CardContent>
                      </Card>
                    ) : !autoGeneratedProfile ? (
                      <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 shadow-lg rounded-3xl">
                        <CardContent className="p-6 text-center">
                          <Info className="w-12 h-12 text-amber-600 mx-auto mb-4" />
                          <h3 className="text-amber-900 font-semibold mb-2 text-xl">Generating Your Scrying Profile</h3>
                          <p className="text-slate-700 mb-4">
                            We're gazing into the vision to create your personalized scrying profile based on your birth details.
                          </p>
                          <Button
                            onClick={generateAutoProfile}
                            disabled={isLoading}
                            className="bg-amber-500 hover:bg-amber-600 text-white font-semibold rounded-xl"
                          >
                            {isLoading ? (
                              <>
                                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                Generating...
                              </>
                            ) : (
                              <>
                                <Sparkles className="w-4 h-4 mr-2" />
                                Generate My Scrying Profile
                              </>
                            )}
                          </Button>
                        </CardContent>
                      </Card>
                    ) : (
                      <div className="space-y-6">
                        {/* Primary Vision */}
                        <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 hover:border-amber-400 shadow-lg rounded-3xl">
                          <CardHeader className="bg-gradient-to-r from-amber-100 to-yellow-100 rounded-t-3xl">
                            <CardTitle className="text-amber-900 flex items-center gap-2">
                              <Gem className="h-5 w-5 text-amber-700" />
                              Your Scrying Profile
                            </CardTitle>
                          </CardHeader>
                          <CardContent className="bg-gradient-to-br from-amber-50 to-yellow-50 space-y-4">
                            <div className="prose max-w-none">
                              <p className="text-slate-700 text-lg leading-relaxed">
                                {autoGeneratedProfile.primaryVision}
                              </p>
                            </div>
                          </CardContent>
                        </Card>

                        {/* Symbols */}
                        <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 hover:border-amber-400 shadow-lg rounded-3xl">
                          <CardHeader className="bg-gradient-to-r from-amber-100 to-yellow-100 rounded-t-3xl">
                            <CardTitle className="text-amber-900 flex items-center gap-2">
                              <Sparkles className="h-5 w-5 text-amber-700" />
                              Your Personal Symbols
                            </CardTitle>
                          </CardHeader>
                          <CardContent className="bg-gradient-to-br from-amber-50 to-yellow-50">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                              {autoGeneratedProfile.symbols.map((symbol, index) => (
                                <div key={index} className="bg-white/60 border-2 border-amber-200 rounded-xl p-4 hover:border-amber-300 transition-all">
                                  <div className="flex items-start gap-3">
                                    {symbol.type === 'color' && <Palette className="h-5 w-5 text-amber-600 mt-0.5" />}
                                    {symbol.type === 'shape' && <Shapes className="h-5 w-5 text-amber-600 mt-0.5" />}
                                    {symbol.type === 'image' && <ImageIcon className="h-5 w-5 text-amber-600 mt-0.5" />}
                                    {symbol.type === 'movement' && <Wind className="h-5 w-5 text-amber-600 mt-0.5" />}
                                    <div className="flex-1">
                                      <h4 className="text-amber-900 font-semibold capitalize mb-1">{symbol.value}</h4>
                                      <p className="text-slate-700 text-sm mb-1">{symbol.meaning}</p>
                                      <p className="text-slate-600 text-xs">{symbol.interpretation}</p>
                                    </div>
                                  </div>
                                </div>
                              ))}
                            </div>
                          </CardContent>
                        </Card>

                        {/* Detailed Interpretation */}
                        <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 hover:border-amber-400 shadow-lg rounded-3xl">
                          <CardHeader className="bg-gradient-to-r from-amber-100 to-yellow-100 rounded-t-3xl">
                            <CardTitle className="text-amber-900 flex items-center gap-2">
                              <BookOpen className="h-5 w-5 text-amber-700" />
                              Detailed Interpretation
                            </CardTitle>
                          </CardHeader>
                          <CardContent className="bg-gradient-to-br from-amber-50 to-yellow-50">
                            <ScrollArea className="h-64">
                              <div className="prose max-w-none">
                                <p className="text-slate-700 leading-relaxed whitespace-pre-line">
                                  {autoGeneratedProfile.detailedInterpretation}
                                </p>
                              </div>
                            </ScrollArea>
                          </CardContent>
                        </Card>

                        {/* Life Path Insights */}
                        {autoGeneratedProfile.lifePathInsights.length > 0 && (
                          <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 hover:border-amber-400 shadow-lg rounded-3xl">
                            <CardHeader className="bg-gradient-to-r from-amber-100 to-yellow-100 rounded-t-3xl">
                              <CardTitle className="text-amber-900 flex items-center gap-2">
                                <Compass className="h-5 w-5 text-amber-700" />
                                Life Path Insights
                              </CardTitle>
                            </CardHeader>
                            <CardContent className="bg-gradient-to-br from-amber-50 to-yellow-50">
                              <ul className="space-y-2">
                                {autoGeneratedProfile.lifePathInsights.map((insight, index) => (
                                  <li key={index} className="flex items-start gap-2 text-slate-700">
                                    <Star className="h-4 w-4 text-amber-600 mt-1 flex-shrink-0" />
                                    <span>{insight}</span>
                                  </li>
                                ))}
                              </ul>
                            </CardContent>
                          </Card>
                        )}
                      </div>
                    )}
                  </TabsContent>
                </motion.div>
              )}

              {/* Scrying Session Tab */}
              {activeTab === 'session' && (
                <motion.div
                  key="session"
                  initial={prefersReducedMotion ? {} : { opacity: 0, y: 20 }}
                  animate={prefersReducedMotion ? {} : { opacity: 1, y: 0 }}
                  exit={prefersReducedMotion ? {} : { opacity: 0, y: -20 }}
                  transition={motionConfig}
                >
                  <TabsContent value="session" className="space-y-6 mt-6">
                    <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 hover:border-amber-400 shadow-lg rounded-3xl">
                      <CardHeader className="bg-gradient-to-r from-amber-100 to-yellow-100 rounded-t-3xl">
                        <CardTitle className="text-amber-900 flex items-center gap-2">
                          <Sparkles className="h-5 w-5 text-amber-700" />
                          Perform a Scrying Session
                        </CardTitle>
                      </CardHeader>
                      <CardContent className="bg-gradient-to-br from-amber-50 to-yellow-50 space-y-4">
                        <div>
                          <label className="block text-sm font-medium text-amber-900 mb-2">
                            Your Question
                          </label>
                          <Textarea
                            value={question}
                            onChange={(e) => setQuestion(e.target.value)}
                            placeholder="What vision do you seek?"
                            className="w-full p-3 bg-white border-2 border-amber-200 rounded-xl text-slate-700 placeholder:text-slate-400 focus:ring-2 focus:ring-amber-400 focus:border-amber-400 h-32 resize-none"
                          />
                        </div>
                        
                        {/* Method Selection */}
                        <div>
                          <label className="block text-sm font-medium text-amber-900 mb-2">
                            Scrying Method
                          </label>
                          <div className="grid grid-cols-2 gap-4">
                            {scryingMethods.map((m) => (
                              <motion.button
                                key={m.value}
                                whileHover={prefersReducedMotion ? {} : { scale: 1.02 }}
                                whileTap={prefersReducedMotion ? {} : { scale: 0.98 }}
                                onClick={() => setMethod(m.value)}
                                className={`p-4 rounded-xl border-2 transition-all duration-300 ${
                                  method === m.value
                                    ? `bg-amber-200 border-amber-400 shadow-md`
                                    : 'bg-white border-amber-200 hover:border-amber-300'
                                }`}
                              >
                                <div className="flex flex-col items-center gap-2">
                                  <div className={method === m.value ? "text-amber-700" : "text-amber-600"}>
                                    {m.icon}
                                  </div>
                                  <div className={`font-semibold ${method === m.value ? "text-amber-900" : "text-slate-700"}`}>
                                    {m.label}
                                  </div>
                                  <div className={`text-xs text-center ${method === m.value ? "text-amber-800" : "text-slate-600"}`}>
                                    {m.description}
                                  </div>
                                </div>
                              </motion.button>
                            ))}
                          </div>
                        </div>

                        <Button 
                          onClick={() => performScrying()}
                          disabled={isLoading || !question.trim()}
                          className="w-full bg-amber-500 hover:bg-amber-600 text-white font-semibold rounded-xl"
                        >
                          <RefreshCw className={`h-4 w-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
                          {isLoading ? 'Gazing into the Vision...' : 'Begin Scrying'}
                        </Button>
                      </CardContent>
                    </Card>

                    {/* Error Display */}
                    {error && (
                      <Card className="bg-gradient-to-br from-red-50 to-pink-50 border-2 border-red-300 shadow-lg rounded-3xl">
                        <CardContent className="p-4">
                          <div className="flex items-center gap-2 text-red-600">
                            <AlertTriangle className="h-5 w-5" />
                            <span className="text-red-800">{error}</span>
                          </div>
                        </CardContent>
                      </Card>
                    )}

                    {/* Manual Vision Results */}
                    {vision && (
                      <div className="space-y-6">
                        <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 hover:border-amber-400 shadow-lg rounded-3xl">
                          <CardHeader className="bg-gradient-to-r from-amber-100 to-yellow-100 rounded-t-3xl">
                            <CardTitle className="text-amber-900 flex items-center gap-2">
                              {method === 'crystal-ball' ? <Gem className="h-5 w-5 text-amber-700" /> : <Square className="h-5 w-5 text-amber-700" />}
                              Your Vision
                            </CardTitle>
                          </CardHeader>
                          <CardContent className="bg-gradient-to-br from-amber-50 to-yellow-50 space-y-4">
                            <div>
                              <h3 className="text-lg font-semibold text-amber-900 mb-2">Your Question</h3>
                              <p className="text-slate-700 italic">"{vision.question}"</p>
                            </div>
                            <div>
                              <h3 className="text-lg font-semibold text-amber-900 mb-2">The Vision</h3>
                              <p className="text-amber-700 text-lg font-medium">{vision.primaryVision}</p>
                            </div>
                            <div>
                              <h3 className="text-lg font-semibold text-amber-900 mb-2">Symbols Revealed</h3>
                              <div className="grid grid-cols-2 gap-2 mt-2">
                                {vision.colors.length > 0 && (
                                  <Badge className="bg-amber-200 text-amber-900 border-2 border-amber-300 rounded-xl">
                                    Colors: {vision.colors.join(', ')}
                                  </Badge>
                                )}
                                {vision.images.length > 0 && (
                                  <Badge className="bg-amber-200 text-amber-900 border-2 border-amber-300 rounded-xl">
                                    Images: {vision.images.join(', ')}
                                  </Badge>
                                )}
                              </div>
                            </div>
                            <div>
                              <h3 className="text-lg font-semibold text-amber-900 mb-2">Interpretation</h3>
                              <ScrollArea className="h-48">
                                <p className="text-slate-700 leading-relaxed whitespace-pre-line">
                                  {vision.detailedInterpretation}
                                </p>
                              </ScrollArea>
                            </div>
                          </CardContent>
                        </Card>
                      </div>
                    )}
                  </TabsContent>
                </motion.div>
              )}

              {/* Guidance Tab */}
              {activeTab === 'guidance' && (
                <motion.div
                  key="guidance"
                  initial={prefersReducedMotion ? {} : { opacity: 0, y: 20 }}
                  animate={prefersReducedMotion ? {} : { opacity: 1, y: 0 }}
                  exit={prefersReducedMotion ? {} : { opacity: 0, y: -20 }}
                  transition={motionConfig}
                >
                  <TabsContent value="guidance" className="space-y-6 mt-6">
                    {currentVision ? (
                      <div className="space-y-6">
                        {/* Insights */}
                        <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 hover:border-amber-400 shadow-lg rounded-3xl">
                          <CardHeader className="bg-gradient-to-r from-amber-100 to-yellow-100 rounded-t-3xl">
                            <CardTitle className="text-amber-900 flex items-center gap-2">
                              <Lightbulb className="h-5 w-5 text-amber-700" />
                              Insights
                            </CardTitle>
                          </CardHeader>
                          <CardContent className="bg-gradient-to-br from-amber-50 to-yellow-50">
                            <ul className="space-y-2">
                              {currentVision.insights.map((insight, index) => (
                                <li key={index} className="flex items-start gap-2 text-slate-700">
                                  <Sparkles className="h-4 w-4 text-amber-600 mt-1 flex-shrink-0" />
                                  <span>{insight}</span>
                                </li>
                              ))}
                            </ul>
                          </CardContent>
                        </Card>

                        {/* Guidance */}
                        <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 hover:border-amber-400 shadow-lg rounded-3xl">
                          <CardHeader className="bg-gradient-to-r from-amber-100 to-yellow-100 rounded-t-3xl">
                            <CardTitle className="text-amber-900 flex items-center gap-2">
                              <Compass className="h-5 w-5 text-amber-700" />
                              Guidance
                            </CardTitle>
                          </CardHeader>
                          <CardContent className="bg-gradient-to-br from-amber-50 to-yellow-50">
                            <ul className="space-y-2">
                              {currentVision.guidance.map((guidance, index) => (
                                <li key={index} className="flex items-start gap-2 text-slate-700">
                                  <Star className="h-4 w-4 text-amber-600 mt-1 flex-shrink-0" />
                                  <span>{guidance}</span>
                                </li>
                              ))}
                            </ul>
                          </CardContent>
                        </Card>

                        {/* Recommendations */}
                        <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 hover:border-amber-400 shadow-lg rounded-3xl">
                          <CardHeader className="bg-gradient-to-r from-amber-100 to-yellow-100 rounded-t-3xl">
                            <CardTitle className="text-amber-900 flex items-center gap-2">
                              <Target className="h-5 w-5 text-amber-700" />
                              Recommendations
                            </CardTitle>
                          </CardHeader>
                          <CardContent className="bg-gradient-to-br from-amber-50 to-yellow-50">
                            <ul className="space-y-2">
                              {currentVision.recommendations.map((rec, index) => (
                                <li key={index} className="flex items-start gap-2 text-slate-700">
                                  <CheckCircle className="h-4 w-4 text-amber-600 mt-1 flex-shrink-0" />
                                  <span>{rec}</span>
                                </li>
                              ))}
                            </ul>
                          </CardContent>
                        </Card>

                        {/* Timing */}
                        <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 hover:border-amber-400 shadow-lg rounded-3xl">
                          <CardHeader className="bg-gradient-to-r from-amber-100 to-yellow-100 rounded-t-3xl">
                            <CardTitle className="text-amber-900 flex items-center gap-2">
                              <Clock className="h-5 w-5 text-amber-700" />
                              Timing & Phases
                            </CardTitle>
                          </CardHeader>
                          <CardContent className="bg-gradient-to-br from-amber-50 to-yellow-50 space-y-4">
                            <div>
                              <h4 className="text-amber-900 font-semibold mb-2">Current Phase</h4>
                              <p className="text-slate-700">{currentVision.currentPhase}</p>
                            </div>
                            <div>
                              <h4 className="text-amber-900 font-semibold mb-2">Favorable Periods</h4>
                              <ul className="space-y-1">
                                {currentVision.favorablePeriods.map((period, index) => (
                                  <li key={index} className="text-slate-700 flex items-start gap-2">
                                    <Star className="h-3 w-3 text-amber-600 mt-1.5 flex-shrink-0" />
                                    <span>{period}</span>
                                  </li>
                                ))}
                              </ul>
                            </div>
                            <div>
                              <h4 className="text-amber-900 font-semibold mb-2">Opportunities</h4>
                              <ul className="space-y-1">
                                {currentVision.opportunities.map((opp, index) => (
                                  <li key={index} className="text-slate-700 flex items-start gap-2">
                                    <Sparkles className="h-3 w-3 text-amber-600 mt-1.5 flex-shrink-0" />
                                    <span>{opp}</span>
                                  </li>
                                ))}
                              </ul>
                            </div>
                          </CardContent>
                        </Card>

                        {/* Spiritual Guidance */}
                        {currentVision.spiritualGuidance && currentVision.spiritualGuidance.length > 0 && (
                          <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 hover:border-amber-400 shadow-lg rounded-3xl">
                            <CardHeader className="bg-gradient-to-r from-amber-100 to-yellow-100 rounded-t-3xl">
                              <CardTitle className="text-amber-900 flex items-center gap-2">
                                <Gem className="h-5 w-5 text-amber-700" />
                                Spiritual Guidance
                              </CardTitle>
                            </CardHeader>
                            <CardContent className="bg-gradient-to-br from-amber-50 to-yellow-50">
                              <ul className="space-y-2">
                                {currentVision.spiritualGuidance.map((guidance, index) => (
                                  <li key={index} className="flex items-start gap-2 text-slate-700">
                                    <Gem className="h-4 w-4 text-amber-600 mt-1 flex-shrink-0" />
                                    <span>{guidance}</span>
                                  </li>
                                ))}
                              </ul>
                            </CardContent>
                          </Card>
                        )}
                      </div>
                    ) : (
                      <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 shadow-lg rounded-3xl">
                        <CardContent className="p-6 text-center">
                          <Info className="w-12 h-12 text-amber-600 mx-auto mb-4" />
                          <h3 className="text-amber-900 font-semibold mb-2 text-xl">No Vision Available</h3>
                          <p className="text-slate-700 mb-4">
                            {hasCompleteProfile 
                              ? 'Generate your scrying profile or perform a scrying session to see guidance.'
                              : 'Complete your profile to generate your scrying profile, or perform a manual scrying session.'}
                          </p>
                        </CardContent>
                      </Card>
                    )}
                  </TabsContent>
                </motion.div>
              )}

              {/* Ask the Seer Tab */}
              {activeTab === 'ask-the-seer' && (
                <motion.div
                  key="ask-the-seer"
                  initial={prefersReducedMotion ? {} : { opacity: 0, y: 20 }}
                  animate={prefersReducedMotion ? {} : { opacity: 1, y: 0 }}
                  exit={prefersReducedMotion ? {} : { opacity: 0, y: -20 }}
                  transition={motionConfig}
                >
                  <TabsContent value="ask-the-seer" className="space-y-6 mt-6">
                    <Card className="bg-gradient-to-br from-amber-50 to-yellow-50 border-2 border-amber-300 hover:border-amber-400 shadow-lg rounded-3xl overflow-hidden">
                      <div className="h-1 bg-amber-400" />
                      <CardHeader className="bg-gradient-to-r from-amber-100 to-yellow-100">
                        <CardTitle className="text-amber-900 flex items-center gap-2">
                          <MessageCircle className="w-5 h-5 text-amber-700" />
                          Ask The Seer About Scrying
                        </CardTitle>
                      </CardHeader>
                      <CardContent className="bg-gradient-to-br from-amber-50 to-yellow-50">
                        {user?.uid ? (
                          <ScryingSeerChatInterface
                            userId={user.uid}
                            userProfile={userProfile}
                            scryingVision={currentVision}
                            scryingMethod={method}
                          />
                        ) : (
                          <div className="text-center py-8">
                            <Info className="w-12 h-12 text-amber-600 mx-auto mb-4" />
                            <p className="text-slate-700">Please sign in to use Ask the Seer</p>
                          </div>
                        )}
                      </CardContent>
                    </Card>
                  </TabsContent>
                </motion.div>
              )}
            </AnimatePresence>
          </Tabs>
        </div>
      </div>
    </div>
  )
}
