import { doc, setDoc, getDoc } from 'firebase/firestore'
import { db } from '@/lib/firebase'

export interface ScryingSymbol {
  type: 'color' | 'shape' | 'image' | 'movement' | 'number' | 'animal' | 'element'
  value: string
  meaning: string
  interpretation: string
  element?: 'fire' | 'water' | 'air' | 'earth'
  energy: number // 1-10 scale
}

export interface ScryingVision {
  id: string
  timestamp: Date
  method: 'crystal-ball' | 'mirror'
  question?: string // Optional for auto-generated readings
  isAutoGenerated: boolean
  displayName?: string
  
  // Vision components
  primaryVision: string
  symbols: ScryingSymbol[]
  colors: string[]
  shapes: string[]
  images: string[]
  movements: string[]
  
  // Interpretation
  overallVision: string
  detailedInterpretation: string
  symbolicMeaning: string
  
  // Guidance
  insights: string[]
  guidance: string[]
  recommendations: string[]
  
  // Timing and energy
  energyLevel: number // 1-100
  currentPhase: string
  favorablePeriods: string[]
  challenges: string[]
  opportunities: string[]
  
  // Personalization
  personalSymbols: string[]
  lifePathInsights: string[]
  spiritualGuidance: string[]
  
  confidenceLevel: number // 1-100
}

class ScryingIntelligence {
  // Symbol database for scrying
  private colorMeanings: Record<string, { meaning: string; interpretation: string; element: 'fire' | 'water' | 'air' | 'earth'; energy: number }> = {
    'deep blue': { meaning: 'Wisdom, intuition, spiritual depth', interpretation: 'Indicates deep spiritual connection and intuitive understanding', element: 'water', energy: 8 },
    'golden yellow': { meaning: 'Divine guidance, enlightenment, prosperity', interpretation: 'Signals divine protection and spiritual awakening', element: 'fire', energy: 9 },
    'silver': { meaning: 'Intuition, reflection, feminine energy', interpretation: 'Represents intuitive insights and emotional clarity', element: 'water', energy: 7 },
    'purple': { meaning: 'Spirituality, mysticism, higher consciousness', interpretation: 'Connects to spiritual realms and psychic abilities', element: 'air', energy: 8 },
    'green': { meaning: 'Growth, healing, nature, balance', interpretation: 'Indicates growth opportunities and healing processes', element: 'earth', energy: 7 },
    'red': { meaning: 'Passion, energy, action, vitality', interpretation: 'Signals strong energy and passionate pursuits', element: 'fire', energy: 9 },
    'white': { meaning: 'Purity, clarity, new beginnings', interpretation: 'Represents clarity of purpose and fresh starts', element: 'air', energy: 8 },
    'black': { meaning: 'Mystery, protection, hidden knowledge', interpretation: 'Reveals hidden truths and protective energies', element: 'earth', energy: 6 },
    'indigo': { meaning: 'Psychic ability, deep insight, spiritual awareness', interpretation: 'Indicates heightened psychic sensitivity', element: 'water', energy: 9 },
    'orange': { meaning: 'Creativity, enthusiasm, transformation', interpretation: 'Signals creative energy and positive transformation', element: 'fire', energy: 8 }
  }

  private shapeMeanings: Record<string, { meaning: string; interpretation: string; element: 'fire' | 'water' | 'air' | 'earth'; energy: number }> = {
    'circle': { meaning: 'Wholeness, completion, cycles', interpretation: 'Represents completion of cycles and unity', element: 'water', energy: 8 },
    'triangle': { meaning: 'Manifestation, trinity, balance', interpretation: 'Indicates manifestation and threefold balance', element: 'fire', energy: 7 },
    'spiral': { meaning: 'Evolution, growth, transformation', interpretation: 'Signals ongoing evolution and spiritual growth', element: 'air', energy: 9 },
    'star': { meaning: 'Guidance, divine connection, hope', interpretation: 'Represents divine guidance and celestial connection', element: 'air', energy: 9 },
    'crescent': { meaning: 'Intuition, cycles, feminine energy', interpretation: 'Indicates intuitive insights and lunar cycles', element: 'water', energy: 7 },
    'square': { meaning: 'Stability, foundation, structure', interpretation: 'Signals solid foundations and stability', element: 'earth', energy: 6 },
    'diamond': { meaning: 'Clarity, focus, precision', interpretation: 'Represents clarity of vision and focused intention', element: 'earth', energy: 8 },
    'waves': { meaning: 'Emotion, flow, movement', interpretation: 'Indicates emotional flow and life movement', element: 'water', energy: 7 },
    'flame': { meaning: 'Transformation, passion, purification', interpretation: 'Signals transformation through fire energy', element: 'fire', energy: 9 },
    'tree': { meaning: 'Growth, connection, life force', interpretation: 'Represents growth and connection to life force', element: 'earth', energy: 8 }
  }

  private imageMeanings: Record<string, { meaning: string; interpretation: string; element: 'fire' | 'water' | 'air' | 'earth'; energy: number }> = {
    'eye': { meaning: 'Vision, insight, awareness', interpretation: 'Indicates heightened awareness and clear vision', element: 'air', energy: 9 },
    'door': { meaning: 'Opportunity, transition, new paths', interpretation: 'Signals new opportunities and transitions', element: 'air', energy: 8 },
    'bridge': { meaning: 'Connection, transition, linking', interpretation: 'Represents connections between realms or situations', element: 'water', energy: 7 },
    'mountain': { meaning: 'Challenges, achievement, stability', interpretation: 'Indicates challenges leading to achievement', element: 'earth', energy: 7 },
    'river': { meaning: 'Flow, journey, life path', interpretation: 'Signals the flow of life and personal journey', element: 'water', energy: 8 },
    'light': { meaning: 'Illumination, truth, clarity', interpretation: 'Represents illumination and revealed truth', element: 'fire', energy: 9 },
    'key': { meaning: 'Solutions, access, unlocking', interpretation: 'Indicates solutions and unlocking potential', element: 'earth', energy: 8 },
    'mirror': { meaning: 'Reflection, self-awareness, truth', interpretation: 'Signals self-reflection and inner truth', element: 'water', energy: 8 },
    'crystal': { meaning: 'Clarity, healing, amplification', interpretation: 'Represents clarity and amplified energy', element: 'earth', energy: 9 },
    'path': { meaning: 'Direction, journey, destiny', interpretation: 'Indicates life direction and spiritual path', element: 'earth', energy: 7 },
    'clouds': { meaning: 'Dreams, intuition, mystery', interpretation: 'Signals intuitive insights and dream messages', element: 'air', energy: 6 },
    'sun': { meaning: 'Vitality, success, enlightenment', interpretation: 'Represents success and spiritual enlightenment', element: 'fire', energy: 10 },
    'moon': { meaning: 'Intuition, cycles, feminine energy', interpretation: 'Indicates intuitive cycles and feminine wisdom', element: 'water', energy: 8 },
    'stars': { meaning: 'Guidance, destiny, cosmic connection', interpretation: 'Signals cosmic guidance and destiny', element: 'air', energy: 9 },
    'butterfly': { meaning: 'Transformation, rebirth, beauty', interpretation: 'Represents transformation and spiritual rebirth', element: 'air', energy: 8 }
  }

  private movementMeanings: Record<string, { meaning: string; interpretation: string; element: 'fire' | 'water' | 'air' | 'earth'; energy: number }> = {
    'flowing': { meaning: 'Smooth progress, natural flow', interpretation: 'Indicates smooth progress and natural flow', element: 'water', energy: 8 },
    'spinning': { meaning: 'Transformation, cycles, change', interpretation: 'Signals transformation and cyclical change', element: 'air', energy: 7 },
    'rising': { meaning: 'Ascension, growth, elevation', interpretation: 'Represents spiritual ascension and growth', element: 'fire', energy: 9 },
    'falling': { meaning: 'Release, letting go, surrender', interpretation: 'Indicates release and letting go', element: 'water', energy: 6 },
    'pulsing': { meaning: 'Life force, rhythm, heartbeat', interpretation: 'Signals life force and natural rhythm', element: 'earth', energy: 8 },
    'dancing': { meaning: 'Joy, celebration, harmony', interpretation: 'Represents joy and harmonious celebration', element: 'fire', energy: 9 },
    'still': { meaning: 'Peace, meditation, stillness', interpretation: 'Indicates peace and meditative stillness', element: 'earth', energy: 7 },
    'expanding': { meaning: 'Growth, expansion, abundance', interpretation: 'Signals growth and expanding possibilities', element: 'air', energy: 8 },
    'contracting': { meaning: 'Focus, concentration, introspection', interpretation: 'Represents focused concentration and introspection', element: 'earth', energy: 6 },
    'spiraling': { meaning: 'Evolution, spiritual growth', interpretation: 'Indicates ongoing evolution and spiritual growth', element: 'air', energy: 9 }
  }

  private lifePhases = [
    'Awakening',
    'Growth & Discovery',
    'Transformation',
    'Integration & Wisdom',
    'Mastery & Service'
  ]

  private favorablePeriods = [
    'Early morning hours for clarity',
    'Full moon for manifestation',
    'New moon for new beginnings',
    'Spring equinox for renewal',
    'Autumn equinox for reflection',
    'During meditation for deeper insights',
    'At dawn for spiritual connection'
  ]

  private challenges = [
    'Balancing intuition with logic',
    'Trusting inner vision',
    'Releasing doubt and fear',
    'Maintaining focus during meditation',
    'Interpreting symbolic messages'
  ]

  private opportunities = [
    'Deepening intuitive abilities',
    'Connecting with spiritual guides',
    'Gaining clarity on life path',
    'Accessing hidden knowledge',
    'Enhancing psychic sensitivity'
  ]

  // Generate deterministic seed from user data
  private generateSeed(birthDate: string, fullName: string): number {
    const dateHash = birthDate.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0)
    const nameHash = fullName.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0)
    return (dateHash + nameHash) % 1000
  }

  // Seeded random number generator
  private seededRandom(seed: number): () => number {
    let value = seed
    return () => {
      value = (value * 9301 + 49297) % 233280
      return value / 233280
    }
  }

  // Generate symbols based on user profile
  private generateSymbolsFromProfile(birthDate: string, fullName: string, method: 'crystal-ball' | 'mirror'): ScryingSymbol[] {
    const seed = this.generateSeed(birthDate, fullName)
    const random = this.seededRandom(seed)
    
    const symbols: ScryingSymbol[] = []
    
    // Generate 3-5 colors
    const colorKeys = Object.keys(this.colorMeanings)
    const numColors = 3 + Math.floor(random() * 3)
    for (let i = 0; i < numColors; i++) {
      const colorKey = colorKeys[Math.floor(random() * colorKeys.length)]
      const colorData = this.colorMeanings[colorKey]
      symbols.push({
        type: 'color',
        value: colorKey,
        meaning: colorData.meaning,
        interpretation: colorData.interpretation,
        element: colorData.element,
        energy: colorData.energy
      })
    }
    
    // Generate 2-3 shapes
    const shapeKeys = Object.keys(this.shapeMeanings)
    const numShapes = 2 + Math.floor(random() * 2)
    for (let i = 0; i < numShapes; i++) {
      const shapeKey = shapeKeys[Math.floor(random() * shapeKeys.length)]
      const shapeData = this.shapeMeanings[shapeKey]
      symbols.push({
        type: 'shape',
        value: shapeKey,
        meaning: shapeData.meaning,
        interpretation: shapeData.interpretation,
        element: shapeData.element,
        energy: shapeData.energy
      })
    }
    
    // Generate 2-4 images
    const imageKeys = Object.keys(this.imageMeanings)
    const numImages = 2 + Math.floor(random() * 3)
    for (let i = 0; i < numImages; i++) {
      const imageKey = imageKeys[Math.floor(random() * imageKeys.length)]
      const imageData = this.imageMeanings[imageKey]
      symbols.push({
        type: 'image',
        value: imageKey,
        meaning: imageData.meaning,
        interpretation: imageData.interpretation,
        element: imageData.element,
        energy: imageData.energy
      })
    }
    
    // Generate 1-2 movements
    const movementKeys = Object.keys(this.movementMeanings)
    const numMovements = 1 + Math.floor(random() * 2)
    for (let i = 0; i < numMovements; i++) {
      const movementKey = movementKeys[Math.floor(random() * movementKeys.length)]
      const movementData = this.movementMeanings[movementKey]
      symbols.push({
        type: 'movement',
        value: movementKey,
        meaning: movementData.meaning,
        interpretation: movementData.interpretation,
        element: movementData.element,
        energy: movementData.energy
      })
    }
    
    return symbols
  }

  // Generate vision from question (manual scrying)
  private generateSymbolsFromQuestion(question: string, method: 'crystal-ball' | 'mirror'): ScryingSymbol[] {
    const seed = question.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0)
    const random = this.seededRandom(seed)
    
    const symbols: ScryingSymbol[] = []
    
    // Generate symbols based on question
    const colorKeys = Object.keys(this.colorMeanings)
    const numColors = 2 + Math.floor(random() * 2)
    for (let i = 0; i < numColors; i++) {
      const colorKey = colorKeys[Math.floor(random() * colorKeys.length)]
      const colorData = this.colorMeanings[colorKey]
      symbols.push({
        type: 'color',
        value: colorKey,
        meaning: colorData.meaning,
        interpretation: colorData.interpretation,
        element: colorData.element,
        energy: colorData.energy
      })
    }
    
    const imageKeys = Object.keys(this.imageMeanings)
    const numImages = 2 + Math.floor(random() * 2)
    for (let i = 0; i < numImages; i++) {
      const imageKey = imageKeys[Math.floor(random() * imageKeys.length)]
      const imageData = this.imageMeanings[imageKey]
      symbols.push({
        type: 'image',
        value: imageKey,
        meaning: imageData.meaning,
        interpretation: imageData.interpretation,
        element: imageData.element,
        energy: imageData.energy
      })
    }
    
    return symbols
  }

  // Calculate elemental balance
  private calculateElementalBalance(symbols: ScryingSymbol[]): { fire: number; water: number; air: number; earth: number; primary: string; secondary: string } {
    const counts = { fire: 0, water: 0, air: 0, earth: 0 }
    
    symbols.forEach(symbol => {
      if (symbol.element) {
        counts[symbol.element]++
      }
    })
    
    const sorted = Object.entries(counts).sort(([, a], [, b]) => b - a)
    
    return {
      ...counts,
      primary: sorted[0][0],
      secondary: sorted[1][0]
    }
  }

  // Generate personalized vision interpretation
  private generateVisionInterpretation(
    symbols: ScryingSymbol[],
    question: string | undefined,
    displayName: string | undefined,
    isAutoGenerated: boolean,
    method: 'crystal-ball' | 'mirror'
  ): { overallVision: string; detailedInterpretation: string; symbolicMeaning: string } {
    const name = displayName || 'Seeker'
    const greeting = isAutoGenerated 
      ? `Dear ${name}, as I gaze into the ${method === 'crystal-ball' ? 'crystal sphere' : 'reflective mirror'}, your personal scrying profile reveals profound insights about your spiritual path and inner vision.`
      : `Dear ${name}, as I gaze into the ${method === 'crystal-ball' ? 'crystal sphere' : 'reflective mirror'} regarding your question "${question}", the visions that appear speak to your deepest concerns and spiritual guidance.`
    
    const primaryColors = symbols.filter(s => s.type === 'color').slice(0, 2)
    const primaryImages = symbols.filter(s => s.type === 'image').slice(0, 2)
    const primaryShapes = symbols.filter(s => s.type === 'shape').slice(0, 1)
    
    const overallVision = `${greeting} The primary colors that emerge are ${primaryColors.map(c => c.value).join(' and ')}, indicating ${primaryColors.map(c => c.meaning).join(' and ')}. ${primaryImages.length > 0 ? `The images of ${primaryImages.map(i => i.value).join(' and ')} appear, symbolizing ${primaryImages.map(i => i.meaning).join(' and ')}.` : ''}`
    
    let detailedInterpretation = `${greeting}\n\n`
    detailedInterpretation += `The ${method === 'crystal-ball' ? 'crystal sphere' : 'mirror'} reveals a tapestry of symbols and visions that speak directly to your spiritual journey. `
    
    symbols.forEach((symbol, index) => {
      detailedInterpretation += `\n\nThe ${symbol.type} of ${symbol.value} appears, representing ${symbol.meaning}. ${symbol.interpretation}`
    })
    
    detailedInterpretation += `\n\nTogether, these symbols weave a narrative of ${isAutoGenerated ? 'your life path and spiritual purpose' : 'guidance for your question'}. The ${method === 'crystal-ball' ? 'crystal' : 'mirror'} speaks to your inner wisdom and the guidance available to you through intuitive vision.`
    
    const elementalBalance = this.calculateElementalBalance(symbols)
    const symbolicMeaning = `The elemental balance reveals ${elementalBalance.primary} energy as primary, indicating ${elementalBalance.primary === 'fire' ? 'passionate action and transformation' : elementalBalance.primary === 'water' ? 'emotional depth and intuition' : elementalBalance.primary === 'air' ? 'mental clarity and communication' : 'grounded stability and manifestation'}. The secondary ${elementalBalance.secondary} energy complements this, creating a harmonious balance in your spiritual vision.`
    
    return { overallVision, detailedInterpretation, symbolicMeaning }
  }

  // Generate insights and guidance
  private generateGuidance(symbols: ScryingSymbol[], isAutoGenerated: boolean): { insights: string[]; guidance: string[]; recommendations: string[] } {
    const insights: string[] = []
    const guidance: string[] = []
    const recommendations: string[] = []
    
    const highEnergySymbols = symbols.filter(s => s.energy >= 8)
    const elementalBalance = this.calculateElementalBalance(symbols)
    
    if (isAutoGenerated) {
      insights.push('Your personal scrying profile reveals a strong connection to intuitive vision')
      insights.push(`The ${elementalBalance.primary} element dominates your spiritual energy`)
      insights.push('You have natural gifts for accessing spiritual guidance through meditation')
      
      guidance.push('Practice regular scrying sessions to deepen your intuitive connection')
      guidance.push('Trust the symbols and visions that appear during your meditative practice')
      guidance.push('Keep a scrying journal to track patterns and insights over time')
      
      recommendations.push('Create a dedicated space for scrying practice with calming elements')
      recommendations.push('Develop a meditation routine before scrying to enhance receptivity')
      recommendations.push('Work with your dominant element to strengthen your spiritual practice')
    } else {
      insights.push('The visions reveal important guidance for your current situation')
      insights.push(`The ${elementalBalance.primary} energy indicates the nature of guidance received`)
      insights.push('Trust your intuition as you interpret these symbolic messages')
      
      guidance.push('Reflect on how these symbols relate to your question')
      guidance.push('Allow the visions to guide your decision-making process')
      guidance.push('Pay attention to recurring symbols in future scrying sessions')
      
      recommendations.push('Take time to meditate on the meanings revealed')
      recommendations.push('Consider how the guidance applies to your life circumstances')
      recommendations.push('Return to scrying when you need further clarity')
    }
    
    return { insights, guidance, recommendations }
  }

  // Generate personal symbols and life path insights
  private generatePersonalInsights(birthDate: string, fullName: string, symbols: ScryingSymbol[]): { personalSymbols: string[]; lifePathInsights: string[]; spiritualGuidance: string[] } {
    const personalSymbols: string[] = []
    const lifePathInsights: string[] = []
    const spiritualGuidance: string[] = []
    
    // Extract unique symbols
    const uniqueSymbols = Array.from(new Set(symbols.map(s => s.value)))
    personalSymbols.push(...uniqueSymbols.slice(0, 5))
    
    // Generate life path insights based on symbols
    const elementalBalance = this.calculateElementalBalance(symbols)
    
    lifePathInsights.push(`Your spiritual path is marked by ${elementalBalance.primary} energy, indicating ${elementalBalance.primary === 'fire' ? 'a journey of transformation and passionate action' : elementalBalance.primary === 'water' ? 'deep emotional and intuitive development' : elementalBalance.primary === 'air' ? 'mental clarity and spiritual communication' : 'grounded manifestation and practical wisdom'}`)
    
    const highEnergyCount = symbols.filter(s => s.energy >= 8).length
    if (highEnergyCount >= 3) {
      lifePathInsights.push('You possess strong spiritual energy and intuitive gifts')
      lifePathInsights.push('Your connection to the spiritual realm is particularly strong')
    }
    
    spiritualGuidance.push('Your personal symbols serve as guides on your spiritual journey')
    spiritualGuidance.push('Regular scrying practice will deepen your intuitive abilities')
    spiritualGuidance.push('Trust the visions that appear, as they reflect your inner wisdom')
    spiritualGuidance.push('The symbols you see are unique to your spiritual path and purpose')
    
    return { personalSymbols, lifePathInsights, spiritualGuidance }
  }

  // Main method: Generate scrying vision
  async generateVision(
    method: 'crystal-ball' | 'mirror',
    question: string | undefined,
    birthDate: string | undefined,
    fullName: string | undefined,
    displayName?: string
  ): Promise<ScryingVision> {
    const isAutoGenerated = !question && !!birthDate && !!fullName
    
    if (!isAutoGenerated && !question) {
      throw new Error('Either question or birthDate/fullName must be provided')
    }
    
    // Generate symbols
    const symbols = isAutoGenerated && birthDate && fullName
      ? this.generateSymbolsFromProfile(birthDate, fullName, method)
      : question
      ? this.generateSymbolsFromQuestion(question, method)
      : []
    
    // Extract symbol types
    const colors = symbols.filter(s => s.type === 'color').map(s => s.value)
    const shapes = symbols.filter(s => s.type === 'shape').map(s => s.value)
    const images = symbols.filter(s => s.type === 'image').map(s => s.value)
    const movements = symbols.filter(s => s.type === 'movement').map(s => s.value)
    
    // Generate primary vision description
    const primaryVision = isAutoGenerated
      ? `As I gaze into the ${method === 'crystal-ball' ? 'crystal sphere' : 'reflective mirror'}, your personal scrying profile reveals ${colors.length > 0 ? `dominant colors of ${colors.slice(0, 2).join(' and ')}` : 'mystical visions'} and ${images.length > 0 ? `powerful images of ${images.slice(0, 2).join(' and ')}` : 'symbolic messages'} that speak to your spiritual path and inner vision.`
      : `As I gaze into the ${method === 'crystal-ball' ? 'crystal sphere' : 'reflective mirror'} regarding "${question}", the visions reveal ${colors.length > 0 ? colors.slice(0, 2).join(' and ') : 'mystical'} colors and ${images.length > 0 ? `images of ${images.slice(0, 2).join(' and ')}` : 'symbolic guidance'} that provide insight into your question.`
    
    // Generate interpretations
    const interpretations = this.generateVisionInterpretation(symbols, question, displayName, isAutoGenerated, method)
    
    // Generate guidance
    const guidanceData = this.generateGuidance(symbols, isAutoGenerated)
    
    // Generate personal insights if auto-generated
    const personalInsights = isAutoGenerated && birthDate && fullName
      ? this.generatePersonalInsights(birthDate, fullName, symbols)
      : { personalSymbols: [], lifePathInsights: [], spiritualGuidance: [] }
    
    // Calculate energy level
    const avgEnergy = symbols.length > 0
      ? Math.round(symbols.reduce((sum, s) => sum + s.energy, 0) / symbols.length * 10)
      : 70
    
    // Generate timing
    const timing = {
      currentPhase: this.lifePhases[Math.floor(Math.random() * this.lifePhases.length)],
      favorablePeriods: this.favorablePeriods.sort(() => 0.5 - Math.random()).slice(0, 3),
      challenges: this.challenges.sort(() => 0.5 - Math.random()).slice(0, 2),
      opportunities: this.opportunities.sort(() => 0.5 - Math.random()).slice(0, 2)
    }
    
    const vision: ScryingVision = {
      id: Date.now().toString(),
      timestamp: new Date(),
      method,
      question,
      isAutoGenerated,
      displayName,
      primaryVision,
      symbols,
      colors,
      shapes,
      images,
      movements,
      overallVision: interpretations.overallVision,
      detailedInterpretation: interpretations.detailedInterpretation,
      symbolicMeaning: interpretations.symbolicMeaning,
      insights: guidanceData.insights,
      guidance: guidanceData.guidance,
      recommendations: guidanceData.recommendations,
      energyLevel: avgEnergy,
      currentPhase: timing.currentPhase,
      favorablePeriods: timing.favorablePeriods,
      challenges: timing.challenges,
      opportunities: timing.opportunities,
      personalSymbols: personalInsights.personalSymbols,
      lifePathInsights: personalInsights.lifePathInsights,
      spiritualGuidance: personalInsights.spiritualGuidance,
      confidenceLevel: 92
    }
    
    return vision
  }

  // Save reading to Firestore
  async saveReading(userId: string, vision: ScryingVision): Promise<void> {
    if (!db) {
      console.warn('Firebase not initialized, cannot save scrying reading')
      return
    }
    
    try {
      const visionData = {
        ...vision,
        timestamp: vision.timestamp.toISOString(),
        userId
      }
      
      await setDoc(doc(db, 'scryingReadings', `${userId}_${vision.id}`), visionData)
      console.log('✅ Scrying reading saved successfully')
    } catch (error) {
      console.error('Error saving scrying reading:', error)
      throw error
    }
  }

  // Get user's scrying profile (auto-generated)
  async getUserScryingProfile(userId: string): Promise<ScryingVision | null> {
    if (!db) {
      return null
    }
    
    try {
      // Look for auto-generated profile
      const profileRef = doc(db, 'scryingProfiles', userId)
      const profileSnap = await getDoc(profileRef)
      
      if (profileSnap.exists()) {
        const data = profileSnap.data()
        return {
          ...data,
          timestamp: new Date(data.timestamp),
        } as ScryingVision
      }
      
      return null
    } catch (error) {
      console.error('Error fetching scrying profile:', error)
      return null
    }
  }

  // Save user's scrying profile (auto-generated)
  async saveUserScryingProfile(userId: string, vision: ScryingVision): Promise<void> {
    if (!db) {
      console.warn('Firebase not initialized, cannot save scrying profile')
      return
    }
    
    try {
      const profileData = {
        ...vision,
        timestamp: vision.timestamp.toISOString(),
        userId
      }
      
      await setDoc(doc(db, 'scryingProfiles', userId), profileData)
      console.log('✅ Scrying profile saved successfully')
    } catch (error) {
      console.error('Error saving scrying profile:', error)
      throw error
    }
  }
}

export const scryingIntelligence = new ScryingIntelligence()

