"use client"

import { useState, useEffect } from "react"
import { useAuth } from "@/hooks/use-auth"
import { ScryingVision } from "@/lib/scryingIntelligence"

export interface ScryingData {
  vision: ScryingVision | null
  isLoading: boolean
  error: string | null
}

export function useScrying() {
  const { user, userProfile } = useAuth()
  const [question, setQuestion] = useState("")
  const [method, setMethod] = useState<'crystal-ball' | 'mirror'>('crystal-ball')
  const [vision, setVision] = useState<ScryingVision | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [autoGeneratedProfile, setAutoGeneratedProfile] = useState<ScryingVision | null>(null)
  const [isLoadingProfile, setIsLoadingProfile] = useState(false)

  // Check if user has complete profile
  const hasCompleteProfile = userProfile?.birthDate && userProfile?.birthTime && userProfile?.birthPlace

  // Auto-load scrying profile on mount if available
  useEffect(() => {
    if (user?.uid && hasCompleteProfile && !autoGeneratedProfile && !isLoadingProfile) {
      loadScryingProfile()
    }
  }, [user?.uid, hasCompleteProfile])

  const loadScryingProfile = async () => {
    if (!user?.uid) return
    
    setIsLoadingProfile(true)
    setError(null)
    
    try {
      const response = await fetch(`/api/tools/scrying/profile?userId=${user.uid}`)
      
      if (response.ok) {
        const result = await response.json()
        if (result.success && result.data) {
          // Convert timestamp back to Date
          const profileData = {
            ...result.data,
            timestamp: new Date(result.data.timestamp)
          }
          setAutoGeneratedProfile(profileData as ScryingVision)
        }
      }
    } catch (err: any) {
      console.error("Error loading scrying profile:", err)
      // Don't set error for profile loading - it's optional
    } finally {
      setIsLoadingProfile(false)
    }
  }

  async function performScrying(customQuestion?: string, customMethod?: 'crystal-ball' | 'mirror') {
    const scryingQuestion = customQuestion || question
    const scryingMethod = customMethod || method

    // For manual scrying, question is required
    if (!scryingQuestion || !scryingQuestion.trim()) {
      setError("Please enter a question for scrying")
      return
    }

    if (!user) {
      setError("Please log in to use Scrying")
      return
    }

    setIsLoading(true)
    setError(null)

    try {
      const response = await fetch('/api/tools/scrying/reading', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          question: scryingQuestion.trim(),
          method: scryingMethod,
          userId: user.uid,
        }),
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}))
        throw new Error(errorData.error || 'Failed to generate scrying vision')
      }

      const result = await response.json()
      
      if (result.success && result.data) {
        // Convert timestamp back to Date
        const visionData = {
          ...result.data,
          timestamp: new Date(result.data.timestamp)
        }
        setVision(visionData as ScryingVision)
      } else {
        throw new Error(result.error || 'Invalid response from server')
      }
    } catch (err: any) {
      console.error("Error performing scrying:", err)
      setError(err.message || "Failed to perform scrying")
      setVision(null)
    } finally {
      setIsLoading(false)
    }
  }

  async function generateAutoProfile() {
    if (!user?.uid || !hasCompleteProfile) {
      setError("Please complete your profile (birth date, time, and place) to generate your scrying profile")
      return
    }

    setIsLoading(true)
    setError(null)

    try {
      const response = await fetch('/api/tools/scrying/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          userId: user.uid,
          method: method,
        }),
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}))
        throw new Error(errorData.error || 'Failed to generate scrying profile')
      }

      const result = await response.json()
      
      if (result.success && result.data) {
        // Convert timestamp back to Date
        const profileData = {
          ...result.data,
          timestamp: new Date(result.data.timestamp)
        }
        setAutoGeneratedProfile(profileData as ScryingVision)
        setVision(null) // Clear manual vision when profile is generated
      } else {
        throw new Error(result.error || 'Invalid response from server')
      }
    } catch (err: any) {
      console.error("Error generating scrying profile:", err)
      setError(err.message || "Failed to generate scrying profile")
    } finally {
      setIsLoading(false)
    }
  }

  function resetData() {
    setQuestion("")
    setVision(null)
    setError(null)
  }

  function resetProfile() {
    setAutoGeneratedProfile(null)
    setError(null)
  }

  return {
    // State
    question,
    setQuestion,
    method,
    setMethod,
    vision,
    autoGeneratedProfile,
    isLoading,
    isLoadingProfile,
    error,
    hasCompleteProfile,
    
    // Actions
    performScrying,
    generateAutoProfile,
    loadScryingProfile,
    resetData,
    resetProfile,
  }
}

